// 南區設計藝術空間相關校系資料
// 六大設計類別
const CATEGORIES = [
  {
    id: 'visual',
    name: '視覺傳達',
    fullName: '視覺傳達設計',
    color: '#FF5C5C',
    bg: '#FFE3E3',
    icon: '🎨',
    desc: '研究「如何透過視覺媒介精準傳遞訊息與情感」，是所有設計的基礎。',
    core: ['企業識別 CIS / Logo', '包裝設計', '廣告文宣', '書籍裝幀', '字體設計', '插畫設計'],
    jobs: ['平面設計師', '包裝設計師', '品牌企劃', '插畫家'],
  },
  {
    id: 'digital',
    name: '動畫遊戲',
    fullName: '數位媒體與動畫遊戲',
    color: '#7C4DFF',
    bg: '#E8DEFF',
    icon: '🎮',
    desc: '結合視覺藝術與數位科技，專注於動態、時間軸與虛擬環境的視覺呈現。',
    core: ['2D/3D 動畫', '動態圖形 Motion', '遊戲美術', '特效後製', '剪輯分鏡'],
    jobs: ['3D 建模師', '動畫師', '遊戲美術設計師', '影像特效師', '剪輯師'],
  },
  {
    id: 'product',
    name: '工業/產品',
    fullName: '工業與產品設計',
    color: '#FF8A2B',
    bg: '#FFEAD1',
    icon: '🪑',
    desc: '專注於實體產品研發，平衡「美感」「功能」與「量產可行性」。',
    core: ['產品造型', '人因工程', '材料工藝', 'Rhino/SolidWorks', '3D 打樣', '通用設計'],
    jobs: ['工業設計師', '產品外觀設計師', '機構工程師', '文創商品設計師'],
  },
  {
    id: 'space',
    name: '空間環境',
    fullName: '空間與環境設計',
    color: '#1E90FF',
    bg: '#D6ECFF',
    icon: '🏛️',
    desc: '研究人與三維空間的關係，從室內居住環境到都市景觀都在此範疇。',
    core: ['空間動線規劃', '採光與材質', '建築結構法規', '景觀生態', 'CAD/BIM 施工圖'],
    jobs: ['室內設計師', '建築師', '景觀設計師', '展場空間設計師'],
  },
  {
    id: 'fashion',
    name: '時尚織品',
    fullName: '時尚與織品設計',
    color: '#E64980',
    bg: '#FFE0EC',
    icon: '👗',
    desc: '以人體為載體，探討服裝、配件與材質在美學與機能上的可能性。',
    core: ['打版與立體裁剪', '織品材料學', '時尚造型彩妝', '配飾設計', '展演企劃'],
    jobs: ['服裝設計師', '時尚造型師', '面料開發師', '陳列設計師'],
  },
  {
    id: 'interaction',
    name: '互動 UX',
    fullName: '互動與使用者體驗',
    color: '#12B886',
    bg: '#D3F9E8',
    icon: '📱',
    desc: '強調「人與科技產品之間的行為互動與流程體驗」，新興領域。',
    core: ['UI 介面設計', 'UX 體驗設計', '網頁前端', 'VR/AR 互動', '服務設計'],
    jobs: ['UI/UX 設計師', '網頁設計師', '互動藝術家', '產品經理 PM'],
  },
];

// 額外類別（不在六大內，但需要呈現）
const EXTRA_CATEGORIES = [
  { id: 'arts', name: '純藝術', color: '#FAB005', bg: '#FFF3BF', icon: '🖼️' },
  { id: 'performance', name: '表演藝術', color: '#BE4BDB', bg: '#F3D9FA', icon: '🎭' },
  { id: 'management', name: '藝術管理', color: '#8D6748', bg: '#F1E4D2', icon: '📋' },
  { id: 'other', name: '其他相關', color: '#868E96', bg: '#E9ECEF', icon: '✨' },
];

const ALL_CATEGORIES = [...CATEGORIES, ...EXTRA_CATEGORIES];

// 9 校 / ~30 系
const SCHOOLS = [
  {
    id: 'npust', name: '國立屏東科技大學', short: '屏科大', city: '屏東', type: 'public-tech',
    college: '',
    links: {
      admission: 'https://adas.npust.edu.tw/',
      star: 'https://adas.npust.edu.tw/enrollments/day-school-technical-college-star-plan/',
      excellent: 'https://adas.npust.edu.tw/enrollment/110%E5%AD%B8%E5%B9%B4%E5%BA%A6%E6%8A%80%E5%84%AA%E7%94%84%E5%AF%A9%E3%80%81%E6%8A%80%E5%84%AA%E4%BF%9D%E9%80%81/',
    },
    note: '公立科大，課程地圖完整，重實作。',
    track: 'tech',
    trackNote: '標準技職主戰場，截圖四個管道完全適用。',
    paths: ['tech-star', 'tech-excellent', 'tech-select', 'tech-place', 'tech-apply'],
    advice: ['繁星：看校排與校內推薦資格', '技優：看競賽獎項資格', '甄選：備審、作品集、口試 / 實作', '聯登：看統測分數與群類對應'],
    departments: [
      {
        id: 'npust-wood', name: '木材科學與設計系', cats: ['product'],
        url: 'https://wsd.npust.edu.tw/',
        course: 'https://wsd.npust.edu.tw/%E7%B3%BB%E6%89%80%E8%B3%87%E8%A8%8A/%E8%AA%B2%E7%A8%8B%E5%9C%B0%E5%9C%96/',
        tags: ['材質實作', '就業地圖'],
        oneLiner: '官方頁同時放課程地圖 + 就業地圖，學什麼 / 去哪裡一目瞭然。',
        detail: '不只有課表，還有特色核心指標、教育目標、核心能力、課程地圖、就業地圖一起呈現。',
      },
      {
        id: 'npust-fashion', name: '時尚設計與管理系', cats: ['fashion'],
        url: 'https://fdm.npust.edu.tw/',
        course: 'https://fdm.npust.edu.tw/%E8%AA%B2%E7%A8%8B%E8%A6%8F%E5%8A%83/',
        tags: ['111–114 課程地圖', '強實習'],
        oneLiner: '強實習導向：暑期 8 週 / 學期制 5 個月 / 大四原則上要修。',
        detail: '校外實習制度非常完整：暑期實習 8 週 320 小時、學期制實習 5 個月、大四原則上要修校外實習。',
      },
    ],
  },
  {
    id: 'tut', name: '台南應用科技大學', short: '南應大', city: '台南', type: 'private-tech',
    college: '設計學院',
    links: {
      admission: 'https://admissions.tut.edu.tw/',
      college: 'https://design.tut.edu.tw/',
      day: 'https://admissions.tut.edu.tw/p/406-1084-51235,r1748.php?Lang=zh-tw',
      overview: 'https://admissions.tut.edu.tw/p/403-1084-1630-1.php?Lang=zh-tw',
    },
    note: '設計學院系所完整，各系頁直接有招生 + 課程地圖入口。',
    track: 'tech',
    trackNote: '標準技職統測型學校，全管道齊備。',
    paths: ['tech-star', 'tech-select', 'tech-excellent', 'tech-place', 'tech-apply', 'tech-solo'],
    advice: ['室設 / 視傳 / 商品 / 多媒體：留意二階備審與作品呈現', '統測穩可看聯登', '作品 / 面試強：優先衝甄選'],
    departments: [
      {
        id: 'tut-id', name: '室內設計系', cats: ['space'],
        url: 'https://id.tut.edu.tw/',
        course: 'https://id.tut.edu.tw/p/412-1067-1036.php?Lang=zh-tw',
        tags: ['住宅商空', '科目表'],
        oneLiner: '系頁頂端直接放招生資訊與課程地圖。',
        detail: '從官方課程地圖可直接往下看科目表與課表，導覽性佳。',
      },
      {
        id: 'tut-vcd', name: '視覺傳達設計系', cats: ['visual'],
        url: 'https://vcd.tut.edu.tw/',
        course: 'https://vcd.tut.edu.tw/p/412-1068-1014.php?Lang=zh-tw',
        tags: ['課程進路圖', '品牌/平面/包裝/數位'],
        oneLiner: '提供「課程規劃及進路圖」，方便比較畢業出路。',
        detail: '可比較畢業後往品牌、平面、包裝、數位內容哪條路。',
      },
      {
        id: 'tut-pd', name: '商品設計系', cats: ['product'],
        url: 'https://pds.tut.edu.tw/',
        course: 'https://websubjectgen.tut.edu.tw/Uploads/20231020014521-%E5%8F%B0%E5%8D%97%E6%87%89%E7%94%A8%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%B8-110%E6%97%A5%E9%96%93%E9%83%A8%E5%9B%9B%E5%B9%B4%E5%88%B6%E5%95%86%E5%93%81%E8%A8%AD%E8%A8%88%E7%B3%BB%E7%A7%91%E7%9B%AE%E8%A1%A8.pdf',
        tags: ['產品模組', '工藝模組'],
        oneLiner: '含產品設計模組、工藝設計模組、設計實務精進。',
        detail: '不只做商品外觀，同時含產品與工藝方向。',
      },
      {
        id: 'tut-dma', name: '多媒體動畫系', cats: ['digital'],
        url: 'https://dma.tut.edu.tw/',
        course: 'https://dma.tut.edu.tw/p/406-1070-15599,r809.php?Lang=zh-tw',
        tags: ['手繪+3D', '鏡頭語言'],
        oneLiner: '手繪動畫、3D 動畫、角色造形、攝錄剪輯、鏡頭語言。',
        detail: '動畫與影音兼具，從手繪到 3D 與鏡頭敘事都有涵蓋。',
      },
    ],
  },
  {
    id: 'stust', name: '南臺科技大學', short: '南臺', city: '台南', type: 'private-tech',
    college: '數位設計學院',
    links: {
      admission: 'https://recruit.stust.edu.tw/',
      college: 'https://cdd.stust.edu.tw/tc/node/intro2',
      day: 'https://recruit.stust.edu.tw/tc/node/four',
      select: 'https://recruit.stust.edu.tw/tc/node/stust4242',
    },
    note: '私立科大中設計學院最完整之一，業界導向。',
    track: 'tech',
    trackNote: '典型統測升學學校，設計群 / 資傳 / 多媒體完整覆蓋。',
    paths: ['tech-excellent', 'tech-select', 'tech-place', 'tech-apply', 'tech-solo'],
    advice: ['統測群類要先對應正確', '甄選常要學習歷程、備審、作品 / 面試', '分數導向強可同步布局聯登'],
    departments: [
      {
        id: 'stust-ic', name: '資訊傳播系', cats: ['interaction', 'digital'],
        url: 'https://ic.stust.edu.tw/',
        course: 'https://ic.stust.edu.tw/tc/node/timeline',
        tags: ['四年時序表', 'E-MAP'],
        oneLiner: '官方直接提供四技日間部大一到大四時序表。',
        detail: '若你最在意「四年怎麼排課」，這頁面非常實用。',
      },
      {
        id: 'stust-vcd', name: '視覺傳達設計系', cats: ['visual', 'digital'],
        url: 'http://www.techadmi.edu.tw/schools_detail_search.php?psrid=202&seq=4223',
        tags: ['商業', '動畫', '創意生活'],
        oneLiner: '分三組：商業設計、動畫設計、創意生活設計。',
        detail: '課程從手繪、美感訓練延伸到 2D/3D 電腦繪圖、動畫、影音後製，相對完整。',
      },
      {
        id: 'stust-mes', name: '多媒體與電腦娛樂科學系', cats: ['digital', 'interaction'],
        url: 'https://mes.stust.edu.tw/',
        course: 'https://mes.stust.edu.tw/tc/node/MES_Uni',
        tags: ['遊戲產業', '跨領域團隊'],
        oneLiner: '以「數位遊戲產業人才培育」為核心。',
        detail: '低年級先建基礎與遊戲設計技能，中後段重視跨領域團隊整合與就業導向學程。',
      },
      {
        id: 'stust-cpd', name: '創新產品設計系', cats: ['product', 'interaction'],
        url: 'https://cpd.stust.edu.tw/',
        course: 'https://cpd.stust.edu.tw/tc/node/course',
        tags: ['產品+UI/UX', '原型製作'],
        oneLiner: '產品設計 + UI + UX，模型與原型實作並重。',
        detail: '強調與市場需求接軌，會要求模型製作、原型設計、實作。',
      },
    ],
  },
  {
    id: 'ksu', name: '崑山科技大學', short: '崑山', city: '台南', type: 'private-tech',
    college: '創意媒體學院',
    links: {
      admission: 'https://recruit.ksu.edu.tw/',
      college: 'https://recruit.ksu.edu.tw/v/394.html',
      courses: 'https://web.ksu.edu.tw/DAAACIS/page/49804',
      day: 'https://recruit.ksu.edu.tw/list/4',
    },
    note: '創意媒體學院系所多，建議走「各系所課程科目表」總入口。',
    track: 'tech',
    trackNote: '標準技職統測型，四技招生總覽一頁可查全管道。',
    paths: ['tech-star', 'tech-excellent', 'tech-select', 'tech-apply', 'tech-place', 'tech-solo'],
    advice: ['分數穩 → 聯登', '校排強 → 繁星', '有競賽 → 技優', '有作品與口條 → 甄選'],
    departments: [
      {
        id: 'ksu-vcd', name: '視覺傳達設計系', cats: ['visual'],
        url: 'https://www.vcd.ksu.edu.tw/',
        course: 'https://www.vcd.ksu.edu.tw/%E6%95%99%E5%AD%B8%E8%83%BD%E9%87%8F/%E8%AA%B2%E7%A8%8B%E8%A8%AD%E8%A8%88/',
        tags: ['平面+動態+商品'],
        oneLiner: '三主軸：平面媒體、動態媒體、創意商品設計。',
        detail: '課程涵蓋版面、包裝、資訊視覺化、腳本分鏡、2D/3D 動畫、音像設計等，面向很廣。',
      },
      {
        id: 'ksu-vp', name: '視訊傳播設計系', cats: ['digital', 'visual'],
        url: 'https://web.ksu.edu.tw/DAAACIS/page/49804',
        tags: ['影音傳播'],
        oneLiner: '從課程科目表總頁進入查看。',
        detail: '建議直接從崑山「各系所課程科目表」總頁進入。',
      },
      {
        id: 'ksu-sd', name: '空間設計系', cats: ['space'],
        url: 'https://web.ksu.edu.tw/DAAACIS/page/49804',
        tags: ['室內空間'],
        oneLiner: '從課程科目表總頁進入查看。',
        detail: '建議直接從崑山「各系所課程科目表」總頁進入。',
      },
      {
        id: 'ksu-pr', name: '公共關係暨廣告系', cats: ['other'],
        url: 'https://web.ksu.edu.tw/DTCRPAD/page/46537',
        tags: ['品牌', '策略傳播'],
        oneLiner: '偏品牌、傳播與整合企劃，非純設計型。',
        detail: '課程圍繞創意思考、策略傳播、研究調查、品牌形塑四大需求。',
      },
      {
        id: 'ksu-im', name: '互動媒體與數位娛樂系', cats: ['interaction', 'digital'],
        url: 'https://web.ksu.edu.tw/DAAACIS/page/49804',
        tags: ['互動', '數位娛樂'],
        oneLiner: '互動內容 + 數位娛樂方向。',
        detail: '從課程科目表總頁可進入查看完整科目規劃。',
      },
    ],
  },
  {
    id: 'stu', name: '樹德科技大學', short: '樹德', city: '高雄', type: 'private-tech',
    college: '設計學院',
    links: {
      admission: 'https://reg.aca.stu.edu.tw/',
      college: 'https://reg.aca.stu.edu.tw/learning-portfolio-114',
      courses: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
      star: 'https://reg.aca.stu.edu.tw/4d_star_admissions',
    },
    note: '設計學院系所最多元的私立科大，9 系含表演、藝管、電競、美髮。',
    track: 'tech',
    trackNote: '官網分流清楚，截圖四項幾乎全包。',
    paths: ['tech-star', 'tech-excellent', 'tech-select', 'tech-place'],
    advice: ['校排強可看繁星', '技藝競賽得獎看技優', '大多數人主力是甄選', '排志願可搭配聯登'],
    departments: [
      {
        id: 'stu-id', name: '室內設計系', cats: ['space'],
        url: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
        tags: ['室內'],
        oneLiner: '可從歷年課程規劃表查詢四年科目表。',
        detail: '建議直接從「歷年課程規劃表查詢」進入抓取四年科目表。',
      },
      {
        id: 'stu-vcd', name: '視覺傳達設計系', cats: ['visual'],
        url: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
        tags: ['視傳'],
        oneLiner: '可從歷年課程規劃表查詢四年科目表。',
        detail: '建議直接從「歷年課程規劃表查詢」進入抓取四年科目表。',
      },
      {
        id: 'stu-fashion', name: '流行設計系', cats: ['fashion'],
        url: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
        tags: ['流行', '時尚'],
        oneLiner: '流行設計，含時尚與配飾方向。',
        detail: '可從歷年課程規劃表查詢進入。',
      },
      {
        id: 'stu-lpd', name: '生活產品設計系', cats: ['product'],
        url: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
        tags: ['生活產品'],
        oneLiner: '生活產品導向的產品設計。',
        detail: '可從歷年課程規劃表查詢進入。',
      },
      {
        id: 'stu-ag', name: '動畫與遊戲設計系', cats: ['digital'],
        url: 'https://info.stu.edu.tw/aca/teacher/qrycoursedept/qrydeptcourse.asp',
        tags: ['動畫', '遊戲'],
        oneLiner: '動畫 + 遊戲兼具。',
        detail: '可從歷年課程規劃表查詢進入。',
      },
      {
        id: 'stu-pa', name: '表演藝術系', cats: ['performance'],
        url: 'https://reg.aca.stu.edu.tw/learning-portfolio-114',
        tags: ['表演'],
        oneLiner: '表演藝術系，含戲劇、舞蹈、表演創作。',
        detail: '建議從學習歷程專區或招生服務網進入。',
      },
      {
        id: 'stu-am', name: '藝術管理與藝術經紀系', cats: ['management'],
        url: 'http://www.techadmi.edu.tw/schools_detail_search.php?psrid=205&seq=4524',
        tags: ['藝管', '文創產業'],
        oneLiner: '藝術 + 管理 + 產業型，非純創作。',
        detail: '課程分為藝術專業鑑賞、文化政策、文創產業、經營管理四大領域。',
      },
      {
        id: 'stu-esp', name: '電子競技與電腦娛樂科學系', cats: ['digital'],
        url: 'https://reg.aca.stu.edu.tw/learning-portfolio-114',
        tags: ['電競'],
        oneLiner: '電競產業導向科系。',
        detail: '建議從學習歷程專區或歷年課程規劃表進入。',
      },
      {
        id: 'stu-hair', name: '美髮設計與經營系', cats: ['other'],
        url: 'https://reg.aca.stu.edu.tw/learning-portfolio-114',
        tags: ['美髮', '經營'],
        oneLiner: '美髮專業 + 沙龍經營。',
        detail: '建議從學習歷程專區進入。',
      },
    ],
  },
  {
    id: 'csu', name: '正修科技大學', short: '正修', city: '高雄', type: 'private-tech',
    college: '',
    links: {
      admission: 'https://visit.csu.edu.tw/',
      college: 'https://recruit.csu.edu.tw/',
      day: 'https://visit.csu.edu.tw/p/412-1072-1348.php?Lang=zh-tw',
      star: 'https://visit.csu.edu.tw/p/412-1072-1353.php?Lang=zh-tw',
      excellent: 'https://visit.csu.edu.tw/p/412-1072-1355.php?Lang=zh-tw',
      select: 'https://visit.csu.edu.tw/p/412-1072-1354.php?Lang=zh-tw',
      place: 'https://visit.csu.edu.tw/p/412-1072-1357.php?Lang=zh-tw',
    },
    note: '115 學年四技申請：備審 80% + 學測 20%，免面試。',
    track: 'tech',
    trackNote: '官網把四管道分成獨立入口，最好查的一間。',
    paths: ['tech-star', 'tech-excellent', 'tech-select', 'tech-place', 'tech-apply', 'tech-solo'],
    advice: ['視傳 / 數位多媒體：看作品呈現與備審品質', '考試型 → 聯登', '有競賽、證照、成果 → 甄選 / 技優'],
    departments: [
      {
        id: 'csu-vcd', name: '視覺傳達設計系', cats: ['visual', 'product'],
        url: 'https://vcd.csu.edu.tw/',
        course: 'https://vcd.csu.edu.tw/p/412-1137-1091.php?Lang=zh-tw',
        tags: ['品牌溝通', '產品工藝', '數位媒體'],
        oneLiner: '三條鍊結：品牌溝通設計、產品工藝研發、智慧與數位媒體應用。',
        detail: '課程規劃頁可查 114/113/112/111/110 入學課程規畫表。',
      },
      {
        id: 'csu-media', name: '數位多媒體設計系', cats: ['digital', 'interaction'],
        url: 'https://media.csu.edu.tw/',
        course: 'https://www.techadmi.edu.tw/schools_detail_search.php?psrid=211&seq=5012',
        tags: ['影音動畫', '互動遊戲'],
        oneLiner: '主打影音動畫 + 互動遊戲設計。',
        detail: '重點為美術設計、創意互動、動畫設計、遊戲設計等方向。若在猶豫動畫 vs 遊戲 vs 數媒，這系偏整合。',
      },
    ],
  },
  {
    id: 'tnnua', name: '國立臺南藝術大學', short: '南藝大', city: '台南', type: 'public-art',
    college: '視覺藝術學院',
    links: { admission: 'https://www.tnnua.edu.tw/p/412-1000-2026.php?Lang=zh-tw', college: 'https://acad.tnnua.edu.tw/p/412-1003-2770.php?Lang=zh-tw' },
    note: '純藝術 / 工藝 / 創作型校風，作品集很重要。',
    track: 'hybrid',
    trackNote: '同時有一般大學管道與「材創系四技二專甄選」兩條路。',
    paths: ['xuece-star', 'xuece-apply', 'xuece-place', 'special', 'tech-select'],
    advice: ['報材創系：留意四技甄選簡章與作品 / 實作要求', '其他學士班：走繁星 / 申請 / 分發 / 特殊選才', '偏創作型、工藝型學生很適合'],
    departments: [
      {
        id: 'tnnua-mat', name: '材質創作與設計學系', cats: ['product', 'arts'],
        url: 'https://materialarts.tnnua.edu.tw/',
        course: 'https://ap.tnnua.edu.tw/CourseInfo/Course_Map.aspx?DSno=252',
        tags: ['工作室制', '木金陶纖維', '當代創作'],
        oneLiner: '全國第一所以「藝術、工藝、設計整合」為核心的創作系。',
        detail: '基礎材質含木質、金工、陶瓷、纖維、設計，結合美學、攝影與設計實務。主修工作室制，學理與實務並重。',
      },
    ],
  },
  {
    id: 'ncku', name: '國立成功大學', short: '成大', city: '台南', type: 'public-general',
    college: '規劃與設計學院',
    links: { admission: 'https://web.ncku.edu.tw/p/412-1000-211.php?Lang=zh-tw', college: 'https://cpd.ncku.edu.tw/' },
    note: '南區設計學院首選，理論與設計深度並重。',
    track: 'general',
    trackNote: '一般大學體系，主戰場是學測 / 分科 + 學習歷程，不是統測。',
    paths: ['xuece-star', 'xuece-apply', 'xuece-place', 'special'],
    advice: ['先查學士班招生、各系系所補充規定', '備齊作品集 / 學習歷程，建築與工設常需作品或自述', '技高生請另外確認該年度是否開放四技管道'],
    departments: [
      {
        id: 'ncku-arch', name: '建築學系', cats: ['space'],
        url: 'https://www.arch.ncku.edu.tw/',
        course: 'https://class-qry.acad.ncku.edu.tw/crm/course_map/develop.php?dept=E7&opt=1&ctg=A',
        tags: ['長年序列 studio', '建築史論', '都市設計'],
        oneLiner: '空間設計本體，五年制建築訓練。',
        detail: '長年序列式 studio 訓練，從基礎到大四、大五持續有建築設計與建築專題設計，深度極高。適合想走建築設計、空間構築、建築史論、都市設計的人。',
      },
      {
        id: 'ncku-id', name: '工業設計學系', cats: ['product', 'interaction'],
        url: 'https://ide.ncku.edu.tw/',
        course: 'https://ide.ncku.edu.tw/p/426-1160-4.php?Lang=zh-tw',
        tags: ['造形+工程', '人因工程', '設計心理'],
        oneLiner: '不只畫產品，設計 + 工程 + 人因 + 市場整合訓練。',
        detail: '官方招生明寫：招收對造形藝術、工程結構、人體工學、行銷策略、設計心理與感性整合於產品開發設計有興趣的學生。',
      },
      {
        id: 'ncku-up', name: '都市計劃學系', cats: ['space'],
        url: 'https://www.up.ncku.edu.tw/',
        course: 'https://www.up.ncku.edu.tw/%E6%8B%9B%E7%94%9F%E5%B0%88%E5%8D%80/%E5%AD%B8%E5%A3%AB%E7%8F%AD/',
        tags: ['土地使用', 'GIS', '都市設計'],
        oneLiner: '城市與空間系統規劃，含政策與設計交界。',
        detail: '系核心（經濟、統計、圖學）→ 空間規劃理論（土地、都市、交通、區域）→ 方法學（GIS、測量）→ 實作（規劃與設計實習、校外實習）。',
      },
    ],
  },
  {
    id: 'nknu', name: '國立高雄師範大學', short: '高師大', city: '高雄', type: 'public-general',
    college: '藝術學院',
    links: { admission: 'https://c.nknu.edu.tw/aca/Album.aspx?PN=55&PClass=A4004&GI=4', college: 'https://w5.nknu.edu.tw/zh/arts1' },
    note: '藝術專業 + 師資培育 / 穩健課程系統。',
    track: 'general',
    trackNote: '一般大學體系，藝術 / 設計類多有術科或作品要求。',
    paths: ['xuece-star', 'xuece-apply', 'xuece-place', 'special'],
    advice: ['視設 / 美術 / 音樂優先查學士班招生', '注意作品集、術科或面試要求', '技高背景可關注「特殊選才」或公告中的四技管道'],
    departments: [
      {
        id: 'nknu-vd', name: '視覺設計學系', cats: ['visual'],
        url: 'https://nknu-vd.com/',
        course: 'https://nknu-vd.com/%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B/',
        tags: ['完整四年時序', '可比對歷年課表'],
        oneLiner: '官方提供 115/116/117 級不同入學年度課程架構。',
        detail: '完整的視覺傳達設計訓練，可直接對比不同學年度課表差異，是查「四年時序表」最方便的入口之一。',
      },
      {
        id: 'nknu-art', name: '美術學系', cats: ['arts'],
        url: 'https://w5.nknu.edu.tw/zh/arts1',
        course: 'https://w5.nknu.edu.tw/zh/arts1',
        tags: ['純美術', '師培可能'],
        oneLiner: '從藝術學院總頁可進招生 / 課程規劃 / 課程系統表。',
        detail: '藝術學院頁直接連通招生專區、課程規劃、課程系統表，導覽性很好。',
      },
      {
        id: 'nknu-music', name: '音樂學系', cats: ['performance'],
        url: 'https://sso.nknu.edu.tw/Services/Web/Default.aspx?webIdx=31',
        course: 'https://sso.nknu.edu.tw/Services/Web/Default.aspx?webIdx=31&menuId=396',
        tags: ['演奏演唱', '音樂教育', '跨領域'],
        oneLiner: '五大面向：演奏、理論、史學、教育、跨領域。',
        detail: '不只表演，也含音樂教育與師培。五大面向：專業演奏/演唱、音樂理論與創作、音樂史與音樂學、音樂教育、跨領域音樂課程。',
      },
    ],
  },
];

// 升學管道資料
const ADMISSION_DATA = {
  highSchoolToCollege: {
    title: '路線 A · 普通高中 → 一般大學 / 科技大學',
    subtitle: '依「學測」與「分科測驗」為主',
    paths: [
      {
        name: '繁星推薦',
        tag: '在校成績比拼',
        color: '#FF8A2B',
        desc: '依學測檢定標準 + 高一高二在校學業成績全校排名百分比進行比序。',
        good: '社區高中頂尖學生有利',
      },
      {
        name: '申請入學',
        tag: '名額最多',
        color: '#FF5C5C',
        desc: '一階學測成績篩選；二階大學面試、筆試 + 學習歷程檔案審查。',
        good: '主流升學管道',
      },
      {
        name: '分發入學',
        tag: '純看考試',
        color: '#1E90FF',
        desc: '採計學測 + 7 月分科測驗成績，直接填志願分發，不看在校與學習歷程。',
        good: '考試型考生',
      },
      {
        name: '特殊選才',
        tag: '單一天才 / 弱勢',
        color: '#7C4DFF',
        desc: '不看學測與分科成績，完全透過書面審查與面試單獨錄取。',
        good: '單一領域突出者',
      },
    ],
  },
  vocationalToTech: {
    title: '路線 B · 技術高中 / 高職 → 四技二專 / 大學',
    subtitle: '依「統測」為主',
    paths: [
      {
        name: '科技校院繁星計畫',
        tag: '在校排名',
        color: '#FF8A2B',
        desc: '高一至高三在校學業成績排名，不看統測，直接分發至科大。',
        good: '在校成績優秀者',
      },
      {
        name: '技優保送 / 技優甄審',
        tag: '技術大牛通道',
        color: '#12B886',
        desc: '不看統測。全國技能競賽、國際技能競賽或全國技藝競賽前幾名 / 優勝者，直接保送或甄審加分。',
        good: '競賽得獎者',
      },
      {
        name: '甄選入學',
        tag: '名額最多',
        color: '#FF5C5C',
        desc: '一階統測成績篩選；二階科大專題口試、術科 + 學習歷程審查。',
        good: '主流升學管道',
      },
      {
        name: '聯合登記分發',
        tag: '純看成績',
        color: '#1E90FF',
        desc: '完全依統測成績加權後填志願分發。',
        good: '考試型考生',
      },
    ],
  },
  crossBridges: [
    { name: '四技二專申請入學', desc: '普通高中生可用「學測成績」申請科技大學（如台科、北科）。' },
    { name: '青年儲蓄帳戶方案', desc: '高中職畢業後先工作 2–3 年，再透過專案管道免考試進入大學。' },
  ],
};

// 國中 → 高中職管道
const JUNIOR_TO_SENIOR = [
  { name: '免試入學', tag: '名額最多', color: '#FF5C5C',
    items: ['就學區免試入學（大會考超額比序）', '試辦學習區完全免試入學', '直升入學（完全中學內升）', '優先免試入學（區內就近入學）'] },
  { name: '特色招生', tag: '專長 / 學術', color: '#FF8A2B',
    items: ['特色招生考試分發（頂尖高中加考）', '專業群科甄選（高職術科測驗）'] },
  { name: '專長與弱勢扶助', tag: '特殊管道', color: '#7C4DFF',
    items: ['藝才班 / 體育班 / 科學班甄選', '技優甄審（國中技藝競賽）', '五專優先免試 / 聯合免試'] },
];

// 升學管道字典：id -> 顯示名稱、所屬體系
const ADMISSION_PATHS = {
  // 一般大學型（學測 / 分科）
  'xuece-star':   { name: '繁星推薦',   short: '繁星',  system: 'general', color: '#FF8A2B', note: '看在校排名 + 學測檢定' },
  'xuece-apply':  { name: '申請入學',   short: '申請',  system: 'general', color: '#FF5C5C', note: '一階學測篩選 → 二階備審 / 面試' },
  'xuece-place':  { name: '分發入學',   short: '分發',  system: 'general', color: '#1E90FF', note: '學測 + 分科測驗成績填志願' },
  'special':      { name: '特殊選才',   short: '特選',  system: 'general', color: '#7C4DFF', note: '不看學測 / 分科，書審 + 面試' },
  // 技職統測型
  'tech-star':      { name: '科技校院繁星', short: '科繁',   system: 'tech', color: '#FF8A2B', note: '看在校成績排名，不看統測' },
  'tech-excellent': { name: '技優保送 / 甄審', short: '技優', system: 'tech', color: '#12B886', note: '競賽得獎免統測或加分' },
  'tech-select':    { name: '甄選入學',     short: '甄選',   system: 'tech', color: '#FF5C5C', note: '一階統測 → 二階備審 / 作品 / 面試' },
  'tech-place':     { name: '聯合登記分發', short: '聯登',   system: 'tech', color: '#1E90FF', note: '純看統測加權分數' },
  'tech-apply':     { name: '四技申請入學', short: '四技申', system: 'tech', color: '#E64980', note: '普高生用學測申請科大' },
  'tech-solo':      { name: '單獨招生',     short: '獨招',   system: 'tech', color: '#868E96', note: '學校自辦招生' },
};

// 體系標籤
const TRACK_LABELS = {
  general: { name: '一般大學型', short: '一般大學', color: '#7C4DFF', bg: '#E8DEFF', desc: '主戰場：學測 / 分科 + 學習歷程' },
  tech:    { name: '技職統測型', short: '技職統測', color: '#12B886', bg: '#D3F9E8', desc: '主戰場：統測 + 作品集 / 備審' },
  hybrid:  { name: '混合型',     short: '兩條路',   color: '#FF8A2B', bg: '#FFEAD1', desc: '同時走學測與統測管道' },
};

Object.assign(window, { CATEGORIES, EXTRA_CATEGORIES, ALL_CATEGORIES, SCHOOLS, ADMISSION_DATA, JUNIOR_TO_SENIOR, ADMISSION_PATHS, TRACK_LABELS });
